import { Opportunity } from "@/types/opportunity";
import { Hackathon } from "@/types/hackathon";
import { StudentProfile } from "@/types/user";

export const mockStudent: StudentProfile = {
  id: "student-001",
  fullName: "Aarav Sharma",
  email: "aarav.sharma@campus.edu.in",
  avatarUrl: "",
  headline: "B.Tech Computer Science | Full-Stack & Systems Enthusiast",
  college: "Indian Institute of Information Technology",
  degree: "B.Tech Computer Science and Engineering",
  graduatingYear: 2027,
  location: "Bengaluru, Karnataka",
  skills: [
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "PostgreSQL",
    "Python",
    "Tailwind CSS",
    "System Design",
  ],
  resumeFileName: "Aarav_Sharma_Resume_2026.pdf",
  hasCompletedProfile: true,
};

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-01",
    title: "Software Engineering Intern - Frontend",
    company: "Razorpay",
    companyLogoUrl: "",
    type: "internship",
    location: "Bengaluru, Karnataka",
    workMode: "hybrid",
    stipendOrSalary: "₹45,000 / month",
    deadline: "2026-10-18T23:59:59Z",
    daysRemaining: 16,
    originalPostingUrl: "https://razorpay.com/jobs",
    postedAt: "2026-10-01T09:00:00Z",
    tags: ["React", "TypeScript", "Next.js", "Design Systems"],
    descriptionSnippet:
      "Join our core Merchant Dashboard team to build ultra-responsive, accessible payment interfaces used by millions.",
    isSaved: true,
  },
  {
    id: "opp-02",
    title: "Graduate Systems Engineer (2026 Batch)",
    company: "Zerodha",
    companyLogoUrl: "",
    type: "job",
    location: "Bengaluru, Karnataka",
    workMode: "in-office",
    stipendOrSalary: "₹16 - ₹22 LPA",
    deadline: "2026-10-12T18:00:00Z",
    daysRemaining: 10,
    originalPostingUrl: "https://zerodha.com/careers",
    postedAt: "2026-09-28T10:00:00Z",
    tags: ["Go", "PostgreSQL", "Linux", "Distributed Systems"],
    descriptionSnippet:
      "Work directly on Kite order routing engines, high-throughput message brokers, and low-latency infrastructure.",
    isSaved: false,
  },
  {
    id: "opp-03",
    title: "Full-Stack Developer Intern",
    company: "Cred",
    companyLogoUrl: "",
    type: "internship",
    location: "Bengaluru, Karnataka",
    workMode: "hybrid",
    stipendOrSalary: "₹60,000 / month",
    deadline: "2026-10-08T23:59:59Z",
    daysRemaining: 6,
    originalPostingUrl: "https://careers.cred.club",
    postedAt: "2026-09-29T14:30:00Z",
    tags: ["TypeScript", "Node.js", "GraphQL", "Microservices"],
    descriptionSnippet:
      "Build delightful financial product journeys, rewards engines, and secure identity infrastructure.",
    isSaved: true,
  },
  {
    id: "opp-04",
    title: "Associate AI / ML Research Engineer",
    company: "Sarvam AI",
    companyLogoUrl: "",
    type: "job",
    location: "Chennai, Tamil Nadu",
    workMode: "hybrid",
    stipendOrSalary: "₹18 - ₹24 LPA",
    deadline: "2026-10-25T23:59:59Z",
    daysRemaining: 23,
    originalPostingUrl: "https://sarvam.ai/careers",
    postedAt: "2026-09-30T11:00:00Z",
    tags: ["Python", "PyTorch", "LLMs", "Indic Languages"],
    descriptionSnippet:
      "Train foundational speech and language models tailored for Indian linguistic diversity and localized context.",
    isSaved: false,
  },
  {
    id: "opp-05",
    title: "Product Design & Frontend Intern",
    company: "Postman",
    companyLogoUrl: "",
    type: "internship",
    location: "Bengaluru, Karnataka",
    workMode: "remote",
    stipendOrSalary: "₹50,000 / month",
    deadline: "2026-10-05T23:59:59Z",
    daysRemaining: 3,
    originalPostingUrl: "https://postman.com/careers",
    postedAt: "2026-10-01T16:00:00Z",
    tags: ["Figma", "React", "Accessibility", "Tailwind CSS"],
    descriptionSnippet:
      "Collaborate with API platform designers to implement polished developer tool components and interactive specs.",
    isSaved: false,
  },
];

export const mockHackathons: Hackathon[] = [
  {
    id: "hack-01",
    title: "Smart India Hackathon 2026 - Regional Finale",
    organizer: "Ministry of Education & AICTE",
    mode: "in-person",
    location: "IIT Madras Research Park, Chennai",
    startDate: "2026-10-24T09:00:00Z",
    endDate: "2026-10-26T18:00:00Z",
    registrationDeadline: "2026-10-10T23:59:59Z",
    prizePool: "₹15,00,000",
    tags: ["Governance", "FinTech", "Clean Energy", "Hardware"],
    externalUrl: "https://sih.gov.in",
    isRegistered: true,
  },
  {
    id: "hack-02",
    title: "India AI Impact Summit Hackathon",
    organizer: "NASSCOM DeepTech",
    mode: "online",
    startDate: "2026-11-02T10:00:00Z",
    endDate: "2026-11-04T22:00:00Z",
    registrationDeadline: "2026-10-20T23:59:59Z",
    prizePool: "₹10,00,000",
    tags: ["GenAI", "Healthcare", "Agriculture", "OpenSource"],
    externalUrl: "https://nasscom.in/hackathons",
    isRegistered: false,
  },
  {
    id: "hack-03",
    title: "FOSS United City Hackathon",
    organizer: "FOSS United Bengaluru",
    mode: "in-person",
    location: "Bengaluru, Karnataka",
    startDate: "2026-10-14T08:00:00Z",
    endDate: "2026-10-15T20:00:00Z",
    registrationDeadline: "2026-10-07T23:59:59Z",
    prizePool: "₹5,00,000",
    tags: ["Open Source", "Rust", "WebAssembly", "Databases"],
    externalUrl: "https://fossunited.org",
    isRegistered: false,
  },
];
